version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - webnet

  wordpress:
    build: ./wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - webnet

  mariadb:
    build: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

volumes:
  wordpress_data:
  db_data:

networks:
  webnet:
